name: loadingpage
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.3
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/1024px.png"
  web:
    generate: true
    image_path: "assets/icons/1024px.png"
  # windows:
  #   generate: true
  #   image_path: "assets/icons/2.png"
  #   icon_size: 48 # min:48, max:256, default: 
  # flutter pub run flutter_launcher_icons:main

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/icons/icono.jpg
  - assets/icons/512px.png
  - assets/icons/1024px.png
  - assets/icons/Background2.png
  - assets/icons/Background2.png
  - assets/icons/iconE.png
  - assets/icons/iconE1.png
  - assets/images/facebook_480.png
  - assets/images/facebook.png
  - assets/images/google.png
  - assets/images/GitHub2000.png

  fonts:
  - family: MiFuente
    fonts:
    - asset: assets/fonts/MiFuente.ttf
  - family: rdl
    fonts:
    - asset: assets/fonts/Radley-Italic.ttf
